### ISSUE TITLE
Default attribute for chrome url is outdated. 

### ISSUE THREAD

**Issue by pjohnson-ptc** [dhoer/chef-chrome#14]
#<URI::InvalidURIError: windows_package[Google Chrome] (chrome::msi line 2) had an error: URI::InvalidURIError: bad URI(is not URI?): https://dl-ssl.google.com/tag/s/appguid={00000000-0000-0000-0000-000000000000}&iid={00000000-0000-0000-0000-000000000000}&lang=en&browser=4&usagestats=0&appname=Google Chrome&needsadmin=false/dl/chrome/install/googlechromestandaloneenterprise64.msi> had an error:
windows_package[Google Chrome] (chrome::msi line 2) had an error: URI::InvalidURIError: bad URI(is not URI?): https://dl-ssl.google.com/tag/s/appguid={00000000-0000-0000-0000-000000000000}&iid={00000000-0000-0000-0000-000000000000}&lang=en&browser=4&usagestats=0&appname=Google Chrome&needsadmin=false/dl/chrome/install/googlechromestandaloneenterprise64.msi

**Comment by dhoer** [comment]
I just tried the uri and it worked.  I see this about once or twice a year and I think it is due to one of Google's CDNs not be updated correctly.  It will eventually be corrected by Google.  In the meantime, wait a bit before trying and maybe you will get lucky and be able to download again.

![image](https://cloud.githubusercontent.com/assets/648360/21289355/c5327768-c458-11e6-9e37-8f786178de2b.png)

**Comment by pjohnson-ptc** [comment]
Unfortunately it was my mistake.  I looked again and I was still at 1.0.12 ( i thought I had double checked).  moving to 1.2.0 fixed the issue. (or perhaps as you stated the root cause is with Googles CDN.  Either way, thanks for the response.
